// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk8Z-fkVaOVfszjz7eReLLnOaqTpTMbpY',
    appId: '1:1094780376414:web:a1365c16d15db5bafc2bcf',
    messagingSenderId: '1094780376414',
    projectId: 'rh-chat-f3ae3',
    authDomain: 'rh-chat-f3ae3.firebaseapp.com',
    storageBucket: 'rh-chat-f3ae3.firebasestorage.app',
    measurementId: 'G-3K9HN6EV2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjThruT-Ze3xgP_XauotvVXqe5Us6EMB8',
    appId: '1:1094780376414:android:0156d6d9efc104aefc2bcf',
    messagingSenderId: '1094780376414',
    projectId: 'rh-chat-f3ae3',
    storageBucket: 'rh-chat-f3ae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzjjEoVz4JdCtxgHJYXV-CMZgaNowMj8',
    appId: '1:1094780376414:ios:795050a3c39d2d34fc2bcf',
    messagingSenderId: '1094780376414',
    projectId: 'rh-chat-f3ae3',
    storageBucket: 'rh-chat-f3ae3.firebasestorage.app',
    iosBundleId: 'com.example.rhChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEzjjEoVz4JdCtxgHJYXV-CMZgaNowMj8',
    appId: '1:1094780376414:ios:795050a3c39d2d34fc2bcf',
    messagingSenderId: '1094780376414',
    projectId: 'rh-chat-f3ae3',
    storageBucket: 'rh-chat-f3ae3.firebasestorage.app',
    iosBundleId: 'com.example.rhChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk8Z-fkVaOVfszjz7eReLLnOaqTpTMbpY',
    appId: '1:1094780376414:web:a8be1628a92e8c43fc2bcf',
    messagingSenderId: '1094780376414',
    projectId: 'rh-chat-f3ae3',
    authDomain: 'rh-chat-f3ae3.firebaseapp.com',
    storageBucket: 'rh-chat-f3ae3.firebasestorage.app',
    measurementId: 'G-RF3QQ0HH4Z',
  );
}
